name: snakemake_usearch
channels:
  - bioconda
dependencies:
 - snakemake=9.1.6
 - snakemake-executor-plugin-slurm=1.1.0
 - snakedeploy=0.11.0
 - graphviz=12.2.1 # to visualize the DAG
 - perl=5.32.1
 - gzip=1.13
 - filtlong=0.2.1
